apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
  labels:
    app: nextjs-frontend
spec:
  replicas: 1  # single pod for dev
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
    spec:
      containers:
      - name: nextjs-frontend
        image: gcr.io/$PROJECT_ID/nextjs-frontend:latest
        ports:
        - containerPort: 4000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://35.232.162.120"