apiVersion: v1
kind: Service
metadata:
  name: nextjs-frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: nextjs-frontend