steps:
  # Install dependencies
  - name: 'node:18-alpine'
    entrypoint: npm
    args: ['install', '-g', 'pnpm']
  
  - name: 'node:18-alpine'
    entrypoint: pnpm
    args: ['install']

  # Run tests
  - name: 'node:18-alpine'
    entrypoint: pnpm
    args: ['test']

  # Build the application
  - name: 'node:18-alpine'
    entrypoint: pnpm
    args: ['build']

  # Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'PORT=4000',
      '-t', 'gcr.io/$PROJECT_ID/nextjs-frontend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/nextjs-frontend:latest',
      '.'
    ]

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs-frontend:$COMMIT_SHA']
  
  # Update kubernetes deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/nextjs-frontend'
      - 'nextjs-frontend=gcr.io/$PROJECT_ID/nextjs-frontend:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=nextjs-cluster'

images:
  - 'gcr.io/$PROJECT_ID/nextjs-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nextjs-frontend:latest' 