apiVersion: v1
kind: Service
metadata:
  name: nextjs-frontend-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: nextjs-frontend 