apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: social-media
    tier: frontend
spec:
  replicas: 2  # Two replicas for high availability
  selector:
    matchLabels:
      app: social-media
      tier: frontend
  template:
    metadata:
      labels:
        app: social-media
        tier: frontend
    spec:
      containers:
      - name: web-server
        image: gcr.io/[PROJECT_ID]/social-media-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-url
        - name: FIREBASE_CONFIG
          valueFrom:
            secretKeyRef:
              name: firebase-secret
              key: config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 